server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env", "health", "info", "logfile", "loggers", "threaddump"]

spring:
  application:
    name: gateway-service

logging:
  level:
    ROOT: INFO
    za.co.sfh.gateway: DEBUG

application:
  test1: Test 1 val
  test2: test 2 value
  test3: Test 3 value

message:
  hello: '{cipher}AgAUJgbD1E91/xvmR2kTu6Verz1f8qM2i2zCtxtWv58vm7GvCXk5u2c7z0XzxiHMeJvEVG9rY9eBuimAvzVfbiRoiZQhzYJ+IS8otUI0uV2lhbvwAAp2S+3MlTptixCSXyu98ahUvGr1oHV7mYjLJ4Ndd9KwYwtJrRtJ60L1Y4iDzsfud7aW80IywdmfMNBkRXWtkLImpDi2L39eROnruiIEDcV6iOTsKPi4xbx3ap34aCksxCLFJuuoLqWsOXLO7009S6nc6ad80bKpqgbEOqBMk8LFsjT7zXVpzeTMEPmocH5Z6HNr6dNbwZu21856fXBQVIgIx5W0e9Fk6C+IUP2/GNGTuoSsUo4Rqblh8X+RfwGh1CxK/IMopppDrvmVyKaQEcTB9Ow+mEqf0Ben3XQqNS1+TnOZp3iVxXJgloGIj8/8u9JFata0Kl3nHxJX9nnJIMdJm6iVc43jBYylATbCLXavVLHpxmJ4XewYmHHFTGsQfmrqRZEQ5bkU4LXl/9VNFSAyNW9QQTuYEq9YhlAEBERLb9PHB9JCmoNeTzmMRQkmLXVWagKWOUBPOay29H+MfFSqJ02RYHi6PZQBPdgxSk+MBcuzNNkk8tTbx/Khp0q4hNotpiOHN1tXGBzx7Q1Y+ITLnDC9hpjHEsZHw//AwoRu5lqQQWjBAvMSQbRk3rMY3lzA7xkzJktFn0CRDQfPmMqr3KvHf2JED1KJiQTo'