server:
  port: 8083

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env", "health", "info", "logfile", "loggers", "threaddump"]

spring:
  application:
    name: inventory-service

logging:
  level:
    ROOT: INFO
    za.co.sfh.inventory: INFO