server:
  port: 8082

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ["configprops", "env", "health", "info", "logfile", "loggers", "threaddump"]

spring:
  application:
    name: incident-service

logging:
  level:
    ROOT: INFO
    za.co.sfh.incident: INFO